name = "wallet-connect"
main = "src/index.js"
account_id = "f2be778fd9c467b08e40ded5c2c84e16"
workers_dev = true
compatibility_date = "2026-01-01"

[assets]
directory = "app"

[env.production]
name = "wallet-connect-prod"
routes = [
  { pattern = "resolutioncustodialdapp.pages.dev/api/*", zone_name = "resolutioncustodialdapp.pages.dev" }
]
